/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "VueEgret",
  "description": "关于Egret引擎的Vue框架",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ]
  ],
  "pages": [
    {
      "title": "API",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/api/",
      "relativePath": "api/README.md",
      "key": "v-dd8809e8",
      "path": "/api/",
      "headers": [
        {
          "level": 2,
          "title": "全局 API",
          "slug": "全局-api"
        },
        {
          "level": 3,
          "title": "VueEgret.classMain",
          "slug": "vueegret-classmain"
        }
      ]
    },
    {
      "title": "使用文档",
      "frontmatter": {
        "sidebarDepth": 2
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-c7706e70",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "foo",
          "slug": "foo"
        },
        {
          "level": 3,
          "title": "test2",
          "slug": "test2"
        },
        {
          "level": 2,
          "title": "bar",
          "slug": "bar"
        }
      ]
    },
    {
      "title": "Using Vue in Markdown",
      "frontmatter": {},
      "regularPath": "/guide/using-vue.html",
      "relativePath": "guide/using-vue.md",
      "key": "v-2ed079b9",
      "path": "/guide/using-vue.html",
      "headers": [
        {
          "level": 2,
          "title": "Browser API Access Restrictions",
          "slug": "browser-api-access-restrictions"
        },
        {
          "level": 2,
          "title": "",
          "slug": ""
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "tagline": null,
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，使用 Vue 语法糖开发Egret。"
          },
          {
            "title": "易用",
            "details": "使用MVVM设计模式替代传统的MVC，让交互更加方便。"
          },
          {
            "title": "高效",
            "details": "20kB min的文件大小，实现虚拟Node，通过diff算法更新DisplayObject。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-2281933f",
      "path": "/"
    }
  ],
  "themeConfig": {
    "repo": "",
    "editLinks": false,
    "docsDir": "",
    "editLinkText": "",
    "lastUpdated": false,
    "nav": [
      {
        "text": "指南",
        "link": "/guide/"
      },
      {
        "text": "API",
        "link": "/api/"
      },
      {
        "text": "组件",
        "link": "/api/"
      },
      {
        "text": "Github",
        "link": "https://github.com/hsuna/vue-egret"
      }
    ],
    "sidebar": {
      "/guide/": [
        {
          "title": "",
          "collapsable": false,
          "children": [
            "",
            "using-vue"
          ]
        },
        {
          "title": "使用文档",
          "collapsable": false,
          "children": [
            "",
            "using-vue"
          ]
        }
      ]
    }
  }
}